// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm7U7uWw90V4O3mCoc8OZ9nwk1bqZYDHg',
    appId: '1:883893839178:web:7fdad584d7cbe58cdf0db3',
    messagingSenderId: '883893839178',
    projectId: 'hi-bank-assestment',
    authDomain: 'hi-bank-assestment.firebaseapp.com',
    storageBucket: 'hi-bank-assestment.appspot.com',
    measurementId: 'G-YWGKT73LNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4tkHcg7IerA3TlG5aOYHLeqgYcCwABic',
    appId: '1:883893839178:android:f72f4df2560254a3df0db3',
    messagingSenderId: '883893839178',
    projectId: 'hi-bank-assestment',
    storageBucket: 'hi-bank-assestment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7qFcogVDFNBLfg8AwEbbomcC98PTGmPQ',
    appId: '1:883893839178:ios:86710a517547027fdf0db3',
    messagingSenderId: '883893839178',
    projectId: 'hi-bank-assestment',
    storageBucket: 'hi-bank-assestment.appspot.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7qFcogVDFNBLfg8AwEbbomcC98PTGmPQ',
    appId: '1:883893839178:ios:86710a517547027fdf0db3',
    messagingSenderId: '883893839178',
    projectId: 'hi-bank-assestment',
    storageBucket: 'hi-bank-assestment.appspot.com',
    iosBundleId: 'com.example.loginGoogle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDm7U7uWw90V4O3mCoc8OZ9nwk1bqZYDHg',
    appId: '1:883893839178:web:031fd85df4a1e0f2df0db3',
    messagingSenderId: '883893839178',
    projectId: 'hi-bank-assestment',
    authDomain: 'hi-bank-assestment.firebaseapp.com',
    storageBucket: 'hi-bank-assestment.appspot.com',
    measurementId: 'G-0L5DPYK8N8',
  );
}
